lab4 first attempt
avramstefan/Lab_Py101 pull request #3
Opened 2022-08-31 16:14 UTC by irina-nita

2022-09-01 08:29 UTC, RaduNichita requested changes
first round of review is done

2022-09-01 08:29 UTC, RaduNichita commented on lab4_module/task02/task02.py
> +    def to_string(self):
here we can implement `__str__`

2022-09-01 08:29 UTC, RaduNichita commented on lab4_module/checker.py
> +    print("No valid arguments!")
```suggestion
    print("No valid arguments!")
    
```

2022-09-01 08:29 UTC, RaduNichita commented on lab4_module/task01/task01.py
> +def random_points(radius, x_center, y_center):
```suggestion

def random_points(radius, x_center, y_center):
```

2022-09-01 08:29 UTC, RaduNichita commented on lab4_module/README.md
> +#the P3 means colors are in ascii, then 3 columns and 3 rows, then 255 for max color, then RGB triplets
```suggestion
# the P3 means colors are in ascii, then 3 columns and 3 rows, then 255 for max color, then RGB triplets 
```

2022-09-01 08:29 UTC, RaduNichita commented on lab4_module/task01/task01.py
> +def random_points(radius, x_center, y_center):
sa faci si o solutie, te rugam

2022-09-01 08:29 UTC, RaduNichita commented on lab4_module/README.md
> +P3 #file format
```suggestion
P3 # file format
```

2022-09-01 08:29 UTC, RaduNichita commented on lab4_module/README.md
> +output: [0.48334197442603744, 4.286286596848848]
nu afisam output ca lista per se, ci numerele din lista

putem intoarce doua valori in python

2022-09-01 08:29 UTC, RaduNichita commented on lab4_module/README.md
> +    2. Numarul de linii (N), respectiv de coloane (M) din body
```suggestion
    2. Numarul de linii `N`, respectiv de coloane `M` din body
```

2022-09-01 08:29 UTC, RaduNichita commented on lab4_module/README.md
> +__Va puteti folosi de modulele math si random.__
foloseste sintaxa obisnuita markdown pentru bold si italic, adica * respectiv **

2022-09-01 08:29 UTC, RaduNichita commented on lab4_module/README.md
> +#the first pixel [255 0 0] means RED = 255, GREEN = 0, BLUE = 0. So the pixel is red.
```suggestion
# the first pixel [255 0 0] means RED = 255, GREEN = 0, BLUE = 0. So the pixel is red. 
```

2022-10-23 14:04 UTC, Vlad1805 commented
Schimba numele directorului in lab_04 te rog.

2023-04-03 15:01 UTC, merged