Added readme + tasks + solved files
avramstefan/Lab_Py101 pull request #4
Opened 2022-09-10 23:41 UTC by sidereal-sky

2022-09-14 21:17 UTC, RaduNichita requested changes

2022-09-14 21:17 UTC, RaduNichita commented on lab_02/task_1/README.md
> +[24, 3, 8, 18, 9, 6, 27]
Input and output should be without [ and ] (just the numbers).

I think it should be good to add the number of numbers as input

2022-09-14 21:17 UTC, RaduNichita commented on lab_02/task_1/README.md
> +sudo chmod 700 checker.py
```suggestion
sudo chmod 644 checker.py
```

2022-09-14 21:17 UTC, RaduNichita commented on lab_02/task_1/solved.py
> +print(task1c(["demigod", "madam", "python", "php"]))
```suggestion
print(task1c(["demigod", "madam", "python", "php"]))

```

2022-09-14 21:17 UTC, RaduNichita commented on lab_02/task_1/task01a.py
> +    # Nu modificati return-ul
```suggestion
    # Nu modificati valoarea de retur a functiei
```

2022-09-14 21:17 UTC, RaduNichita commented on lab_02/task_1/task01c.py
> +
palindromes = []

2022-09-14 21:17 UTC, RaduNichita commented on lab_02/task_3/task03.py
> +    return nume
```suggestion
    return nume
    
```

2022-09-14 21:17 UTC, RaduNichita commented on lab_02/task_2/solved.py
> +print(task(50, 'A', 8.2, 'c', '_', 3, 'n', True, 'Z', 't', [1,2]))
```suggestion
print(task(50, 'A', 8.2, 'c', '_', 3, 'n', True, 'Z', 't', [1,2]))

```

2022-09-14 21:17 UTC, RaduNichita commented on lab_02/task_2/solved.py
> +    numere -> elemente de mai multe tipuri
```suggestion
    numere -> elemente de tipuri diferite
```

2022-09-14 21:17 UTC, RaduNichita commented on lab_02/task_1/README.md
> +* dupa ce se aplica functionale, noul rezultat va fi de tipul "nume_functionala object"
you can give a link with for anyone curious to understand why map/filter/reduce doesn't return a list

2022-09-14 21:17 UTC, RaduNichita commented on lab_02/task_1/README.md
> +["demigod", "madam", "python", "php"]
the input and output should not contain [, ] or ".

2022-09-14 21:17 UTC, RaduNichita commented on lab_02/task_1/README.md
> +> Pentru testare, puteți rula script-ul direct din IDE sau puteți rula în terminal comanda:
this is not a quote. I think you can leave it without >

2022-09-14 21:17 UTC, RaduNichita commented on lab_02/task_2/README.md
> +sudo chmod 700 checker.py
```suggestion
sudo chmod 644 checker.py
```

2022-09-14 21:17 UTC, RaduNichita commented on lab_02/task_2/task02.py
> +    return result
```suggestion
    return result
    
```

2022-10-23 14:17 UTC, Vlad1805 commented
Adauga un director skel in care sa fie task1, task2 si task3.
Muta fisierele de solved.py intr-un director solved.

2022-10-23 16:15 UTC, merged